# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/guilh/code/optimaltreelabeling

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/guilh/code/optimaltreelabeling

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/guilh/code/optimaltreelabeling/CMakeFiles /mnt/c/Users/guilh/code/optimaltreelabeling/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/guilh/code/optimaltreelabeling/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named OptimalTreeLabeling

# Build rule for target.
OptimalTreeLabeling: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OptimalTreeLabeling
.PHONY : OptimalTreeLabeling

# fast build rule for target.
OptimalTreeLabeling/fast:
	$(MAKE) -f CMakeFiles/OptimalTreeLabeling.dir/build.make CMakeFiles/OptimalTreeLabeling.dir/build
.PHONY : OptimalTreeLabeling/fast

main.o: main.cc.o

.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i

.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s

.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cc.s
.PHONY : main.cc.s

src/label.o: src/label.cpp.o

.PHONY : src/label.o

# target to build an object file
src/label.cpp.o:
	$(MAKE) -f CMakeFiles/OptimalTreeLabeling.dir/build.make CMakeFiles/OptimalTreeLabeling.dir/src/label.cpp.o
.PHONY : src/label.cpp.o

src/label.i: src/label.cpp.i

.PHONY : src/label.i

# target to preprocess a source file
src/label.cpp.i:
	$(MAKE) -f CMakeFiles/OptimalTreeLabeling.dir/build.make CMakeFiles/OptimalTreeLabeling.dir/src/label.cpp.i
.PHONY : src/label.cpp.i

src/label.s: src/label.cpp.s

.PHONY : src/label.s

# target to generate assembly for a file
src/label.cpp.s:
	$(MAKE) -f CMakeFiles/OptimalTreeLabeling.dir/build.make CMakeFiles/OptimalTreeLabeling.dir/src/label.cpp.s
.PHONY : src/label.cpp.s

src/label_multithread.o: src/label_multithread.cpp.o

.PHONY : src/label_multithread.o

# target to build an object file
src/label_multithread.cpp.o:
	$(MAKE) -f CMakeFiles/OptimalTreeLabeling.dir/build.make CMakeFiles/OptimalTreeLabeling.dir/src/label_multithread.cpp.o
.PHONY : src/label_multithread.cpp.o

src/label_multithread.i: src/label_multithread.cpp.i

.PHONY : src/label_multithread.i

# target to preprocess a source file
src/label_multithread.cpp.i:
	$(MAKE) -f CMakeFiles/OptimalTreeLabeling.dir/build.make CMakeFiles/OptimalTreeLabeling.dir/src/label_multithread.cpp.i
.PHONY : src/label_multithread.cpp.i

src/label_multithread.s: src/label_multithread.cpp.s

.PHONY : src/label_multithread.s

# target to generate assembly for a file
src/label_multithread.cpp.s:
	$(MAKE) -f CMakeFiles/OptimalTreeLabeling.dir/build.make CMakeFiles/OptimalTreeLabeling.dir/src/label_multithread.cpp.s
.PHONY : src/label_multithread.cpp.s

src/label_optimally.o: src/label_optimally.cpp.o

.PHONY : src/label_optimally.o

# target to build an object file
src/label_optimally.cpp.o:
	$(MAKE) -f CMakeFiles/OptimalTreeLabeling.dir/build.make CMakeFiles/OptimalTreeLabeling.dir/src/label_optimally.cpp.o
.PHONY : src/label_optimally.cpp.o

src/label_optimally.i: src/label_optimally.cpp.i

.PHONY : src/label_optimally.i

# target to preprocess a source file
src/label_optimally.cpp.i:
	$(MAKE) -f CMakeFiles/OptimalTreeLabeling.dir/build.make CMakeFiles/OptimalTreeLabeling.dir/src/label_optimally.cpp.i
.PHONY : src/label_optimally.cpp.i

src/label_optimally.s: src/label_optimally.cpp.s

.PHONY : src/label_optimally.s

# target to generate assembly for a file
src/label_optimally.cpp.s:
	$(MAKE) -f CMakeFiles/OptimalTreeLabeling.dir/build.make CMakeFiles/OptimalTreeLabeling.dir/src/label_optimally.cpp.s
.PHONY : src/label_optimally.cpp.s

src/labeling.o: src/labeling.cpp.o

.PHONY : src/labeling.o

# target to build an object file
src/labeling.cpp.o:
	$(MAKE) -f CMakeFiles/OptimalTreeLabeling.dir/build.make CMakeFiles/OptimalTreeLabeling.dir/src/labeling.cpp.o
.PHONY : src/labeling.cpp.o

src/labeling.i: src/labeling.cpp.i

.PHONY : src/labeling.i

# target to preprocess a source file
src/labeling.cpp.i:
	$(MAKE) -f CMakeFiles/OptimalTreeLabeling.dir/build.make CMakeFiles/OptimalTreeLabeling.dir/src/labeling.cpp.i
.PHONY : src/labeling.cpp.i

src/labeling.s: src/labeling.cpp.s

.PHONY : src/labeling.s

# target to generate assembly for a file
src/labeling.cpp.s:
	$(MAKE) -f CMakeFiles/OptimalTreeLabeling.dir/build.make CMakeFiles/OptimalTreeLabeling.dir/src/labeling.cpp.s
.PHONY : src/labeling.cpp.s

src/tree.o: src/tree.cpp.o

.PHONY : src/tree.o

# target to build an object file
src/tree.cpp.o:
	$(MAKE) -f CMakeFiles/OptimalTreeLabeling.dir/build.make CMakeFiles/OptimalTreeLabeling.dir/src/tree.cpp.o
.PHONY : src/tree.cpp.o

src/tree.i: src/tree.cpp.i

.PHONY : src/tree.i

# target to preprocess a source file
src/tree.cpp.i:
	$(MAKE) -f CMakeFiles/OptimalTreeLabeling.dir/build.make CMakeFiles/OptimalTreeLabeling.dir/src/tree.cpp.i
.PHONY : src/tree.cpp.i

src/tree.s: src/tree.cpp.s

.PHONY : src/tree.s

# target to generate assembly for a file
src/tree.cpp.s:
	$(MAKE) -f CMakeFiles/OptimalTreeLabeling.dir/build.make CMakeFiles/OptimalTreeLabeling.dir/src/tree.cpp.s
.PHONY : src/tree.cpp.s

src/utils.o: src/utils.cpp.o

.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) -f CMakeFiles/OptimalTreeLabeling.dir/build.make CMakeFiles/OptimalTreeLabeling.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i

.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) -f CMakeFiles/OptimalTreeLabeling.dir/build.make CMakeFiles/OptimalTreeLabeling.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s

.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) -f CMakeFiles/OptimalTreeLabeling.dir/build.make CMakeFiles/OptimalTreeLabeling.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... main"
	@echo "... OptimalTreeLabeling"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/label.o"
	@echo "... src/label.i"
	@echo "... src/label.s"
	@echo "... src/label_multithread.o"
	@echo "... src/label_multithread.i"
	@echo "... src/label_multithread.s"
	@echo "... src/label_optimally.o"
	@echo "... src/label_optimally.i"
	@echo "... src/label_optimally.s"
	@echo "... src/labeling.o"
	@echo "... src/labeling.i"
	@echo "... src/labeling.s"
	@echo "... src/tree.o"
	@echo "... src/tree.i"
	@echo "... src/tree.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

